//! Board generation — hex constants today; full SVG port later.
//!
//! Production laser SVGs still come from Python:
//! - `boards/snub-birch/SnubTriangleBoard.svg.py`
//! - `boards/hex-edge-acrylic/HexEdgeTriangleBoard.svg.py`
//! - `boards/smooth-acrylic/SmoothTriangleBoard.svg.py`

use anyhow::{bail, Result};
use cowsinspace_geom::{HEX_EDGE_ACRYLIC_R_MM, HEX_EDGE_COUNT};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BoardKind {
    SnubBirch,
    HexEdgeAcrylic,
    SmoothAcrylic,
}

impl BoardKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::SnubBirch => "snub-birch",
            Self::HexEdgeAcrylic => "hex-edge-acrylic",
            Self::SmoothAcrylic => "smooth-acrylic",
        }
    }

    pub fn parse(s: &str) -> Result<Self> {
        match s {
            "snub-birch" | "snub" => Ok(Self::SnubBirch),
            "hex-edge-acrylic" | "hex-edge" | "hex" => Ok(Self::HexEdgeAcrylic),
            "smooth-acrylic" | "smooth" => Ok(Self::SmoothAcrylic),
            other => bail!("unknown board kind {other:?} (snub-birch|hex-edge-acrylic|smooth-acrylic)"),
        }
    }

    /// Python regen command from the repo root.
    pub fn python_regen_command(self) -> &'static str {
        match self {
            Self::SnubBirch => "python3 boards/snub-birch/SnubTriangleBoard.svg.py",
            Self::HexEdgeAcrylic => {
                ".venv/bin/python boards/hex-edge-acrylic/HexEdgeTriangleBoard.svg.py"
            }
            Self::SmoothAcrylic => {
                ".venv/bin/python boards/smooth-acrylic/SmoothTriangleBoard.svg.py"
            }
        }
    }
}

/// Hex-edge acrylic production parameters (from `HexEdgeTriangleBoard-panels.json`).
pub struct HexEdgeAcrylicParams {
    pub edge_hex_count: u32,
    pub hex_r_mm: f64,
}

impl Default for HexEdgeAcrylicParams {
    fn default() -> Self {
        Self {
            edge_hex_count: HEX_EDGE_COUNT,
            hex_r_mm: HEX_EDGE_ACRYLIC_R_MM,
        }
    }
}

/// Summarize board parameters (placeholder until SVG generation is ported).
pub fn describe(kind: BoardKind) -> String {
    match kind {
        BoardKind::HexEdgeAcrylic => {
            let p = HexEdgeAcrylicParams::default();
            format!(
                "hex-edge-acrylic: n={} hexes/edge, R={:.2} mm (edge length = R). Regen with:\n  {}",
                p.edge_hex_count,
                p.hex_r_mm,
                kind.python_regen_command()
            )
        }
        other => format!(
            "{}: SVG still generated by Python.\n  {}",
            other.as_str(),
            other.python_regen_command()
        ),
    }
}
